Data Cleaning

In [3]:
import numpy as np 
import pandas as pd

In [4]:
data = pd.read_csv(r"D:/Spam SMS Detection/Dataset/spam.csv",encoding='latin-1') #cuz of UTF-8 encoding problem
display(data.head(10))

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
5,spam,FreeMsg Hey there darling it's been 3 week's n...,NaN,NaN,NaN
6,ham,Even my brother is not like to speak with me. ...,NaN,NaN,NaN
7,ham,As per your request 'Melle Melle (Oru Minnamin...,NaN,NaN,NaN
8,spam,WINNER!! As a valued network customer you have...,NaN,NaN,NaN
9,spam,Had your mobile 11 months or more? U R entitle...,NaN,NaN,NaN

In [5]:
data.shape

(5572, 5)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [7]:
data.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)
data.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
data.rename(columns={'v1': 'target','v2':'text'},inplace=True)
data.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
print("Number of spam and ham values:")
print(data["target"].value_counts())

Number of spam and ham values:
target
ham     4825
spam     747
Name: count, dtype: int64

In [10]:
print("Number of missing values if any : ")
print(data.isnull().sum())

Number of missing values if any :
target    0
text      0
dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data['target'] = encoder.fit_transform(data['target']) #spam=1, ham=0
data.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [12]:
print("Number of duplicate values if any: ")
data.duplicated().sum()

Number of duplicate values if any:

403

In [13]:
print("Remove duplicate values")
data = data.drop_duplicates(keep='first')
data.duplicated().sum()

Remove duplicate values

0

In [14]:
data['num_charac'] = data['text'].str.len()

data.head()

   target                                               text  num_charac
0       0  Go until jurong point, crazy.. Available only ...         111
1       0                      Ok lar... Joking wif u oni...          29
2       1  Free entry in 2 a wkly comp to win FA Cup fina...         155
3       0  U dun say so early hor... U c already then say...          49
4       0  Nah I don't think he goes to usf, he lives aro...          61

In [15]:
#extracting no. of words
import nltk
nltk.download('punkt_tab', quiet=True)
data['num_sentences'] = data['text'].astype(str).apply(lambda x: len(nltk.sent_tokenize(x)))
data.head()

,target,text,num_charac,num_sentences
0,0,"Go until jurong point, crazy.. Available only ...",111,2
1,0,Ok lar... Joking wif u oni...,29,2
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,2
3,0,U dun say so early hor... U c already then say...,49,1
4,0,"Nah I don't think he goes to usf, he lives aro...",61,1

In [16]:
data.describe()

            target   num_charac  num_sentences
count  5169.000000  5169.000000    5169.000000
mean      0.126330    78.977945       1.965564
std       0.332253    58.236293       1.448541
min       0.000000     2.000000       1.000000
25%       0.000000    36.000000       1.000000
50%       0.000000    60.000000       1.000000
75%       0.000000   117.000000       2.000000
max       1.000000   910.000000      38.000000

In [17]:
print("Non-spam messages:")
data[data['target'] == 0][['num_charac','num_sentences']].describe()

Non-spam messages:

        num_charac  num_sentences
count  4516.000000    4516.000000
mean     70.459256       1.820195
std      56.358207       1.383657
min       2.000000       1.000000
25%      34.000000       1.000000
50%      52.000000       1.000000
75%      90.000000       2.000000
max     910.000000      38.000000

In [18]:
print("Spam messages:")
data[data['target'] == 1][['num_charac','num_sentences']].describe()

Spam messages:

       num_charac  num_sentences
count  653.000000     653.000000
mean   137.891271       2.970904
std     30.137753       1.488425
min     13.000000       1.000000
25%    132.000000       2.000000
50%    149.000000       3.000000
75%    157.000000       4.000000
max    224.000000       9.000000

In [19]:
from nltk.corpus import stopwords
import string
from nltk.stem.porter import PorterStemmer as ps

In [20]:
def transform_text(text):
    text = text.lower()
    text = nltk.word_tokenize(text)
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
    text = y[:]
    y.clear()
    for i in text :
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()
    for i in text:
        y.append(ps().stem(i))

    return " ".join(y)

In [21]:
data['text'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [22]:
transform_text("Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...")

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [23]:
data['transformed_text'] = data['text'].apply(transform_text)
data.head()

,target,text,num_charac,num_sentences,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...",111,2,go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,29,2,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,2,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,49,1,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",61,1,nah think goe usf live around though

Model Building

In [24]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB,GaussianNB, BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,recall_score,f1_score

cv = CountVectorizer()
tfidf = TfidfVectorizer()

In [25]:
x = tfidf.fit_transform(data['transformed_text']).toarray()

In [26]:
x.shape

(5169, 6708)

In [27]:
y = data['target'].values
y

array([0, 0, 1, ..., 0, 0, 0])

In [28]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [29]:
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

gnb.fit(x_train,y_train)
y_pred = gnb.predict(x_test)
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Precision:",precision_score(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))

Accuracy: 0.8762088974854932
Precision: 0.5231481481481481
Confusion Matrix:
 [[793 103]
 [ 25 113]]

In [30]:
mnb.fit(x_train,y_train)
y_pred = mnb.predict(x_test)
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Precision:",precision_score(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))

Accuracy: 0.9593810444874274
Precision: 1.0
Confusion Matrix:
 [[896   0]
 [ 42  96]]

In [31]:
bnb.fit(x_train,y_train)
y_pred = bnb.predict(x_test)
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Precision:",precision_score(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))

Accuracy: 0.9700193423597679
Precision: 0.9734513274336283
Confusion Matrix:
 [[893   3]
 [ 28 110]]

In [32]:

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [33]:
svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear', penalty='l1')
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
bc = BaggingClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
xgb = XGBClassifier(n_estimators=50,random_state=2)

In [34]:
clfs = {
    'SVC' : svc,
    'KN' : knc, 
    'NB': mnb, 
    'DT': dtc, 
    'LR': lrc, 
    'RF': rfc, 
    'AdaBoost': abc, 
    'BgC': bc, 
    'ETC': etc,
    'GBDT':gbdt,
    'xgb':xgb
}

In [35]:
def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred)
    
    return accuracy,precision

In [36]:
train_classifier(svc,x_train,y_train,x_test,y_test)

(0.9729206963249516, 0.9741379310344828)

In [37]:
accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():
    
    current_accuracy,current_precision = train_classifier(clf, x_train,y_train,x_test,y_test)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For  SVC
Accuracy -  0.9729206963249516
Precision -  0.9741379310344828
For  KN
Accuracy -  0.9003868471953579
Precision -  1.0
For  NB
Accuracy -  0.9593810444874274
Precision -  1.0
For  DT
Accuracy -  0.9361702127659575
Precision -  0.8461538461538461
For  LR
Accuracy -  0.9516441005802708
Precision -  0.94
For  RF
Accuracy -  0.971953578336557
Precision -  1.0

c:\Users\anami\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

For  AdaBoost
Accuracy -  0.9613152804642167
Precision -  0.9454545454545454
For  BgC
Accuracy -  0.9584139264990329
Precision -  0.8625954198473282
For  ETC
Accuracy -  0.9729206963249516
Precision -  0.9824561403508771
For  GBDT
Accuracy -  0.9526112185686654
Precision -  0.9238095238095239
For  xgb
Accuracy -  0.9748549323017408
Precision -  0.9516129032258065

In [38]:
performance_data = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)
performance_data

   Algorithm  Accuracy  Precision
1         KN  0.900387   1.000000
2         NB  0.959381   1.000000
5         RF  0.971954   1.000000
8        ETC  0.972921   0.982456
0        SVC  0.972921   0.974138
10       xgb  0.974855   0.951613
6   AdaBoost  0.961315   0.945455
4         LR  0.951644   0.940000
9       GBDT  0.952611   0.923810
7        BgC  0.958414   0.862595
3         DT  0.936170   0.846154

In [39]:
print("Best performing algorithm based on precision score: Random Forest Classifier with precision score of 1.0 and accuracy 97.1%")

Best performing algorithm based on precision score: Random Forest Classifier with precision score of 1.0 and accuracy 97.1%

In [ ]:
import pickle
pickle.dump(rfc,open('model.pkl','wb'))